### ISSUE TITLE
"Copy code" button does not copy code to clipboard

### ISSUE THREAD

**Issue by csjaugustus** [7gxycn08/ChatGPT-Desktop-Webview#1]
The button doesn't seem to work like it does on the webpage version. You would have to manually highlight and copy the code.

**Comment by 7gxycn08** [comment]
Isn't that the same behavior as the website?

**Comment by 7gxycn08** [comment]
> The button doesn't seem to work like it does on the webpage version. You would have to manually highlight and copy the code.

Isn't that the same behavior as the website? as in you highlight text, right click then press copy?

**Comment by csjaugustus** [comment]
> > The button doesn't seem to work like it does on the webpage version. You would have to manually highlight and copy the code.
> 
> Isn't that the same behavior as the website? as in you highlight text, right click then press copy?

On the website you can simply click the "copy code" button. I'm referring to code specifically. There's a "copy code" button on the top right corner that only works on the website.

**Comment by 7gxycn08** [comment]
> 

Yep just noticed that i'll look into it and report back. Thanks for pointing it out.

**Comment by 7gxycn08** [comment]
> On the website you can simply click the "copy code" button. I'm referring to code specifically. There's a "copy code" button on the top right corner that only works on the website.

Yep just noticed that i'll look into it and report back. Thanks for pointing it out.

**Comment by 7gxycn08** [comment]
Ok found a solution for this problem in javascript code from the website cannot access the clipboard by default so enabling access in the Webengine settings fixed the issue now the button works normally.

`self.settings = QWebEngineSettings.globalSettings()
 self.settings.setAttribute(QWebEngineSettings.WebAttribute.JavascriptCanAccessClipboard,True)`

**Comment by 7gxycn08** [comment]
@csjaugustus Just updated the source code with a fix and released a new compiled executable v1.0.0.2 you can try it out now.

**Comment by csjaugustus** [comment]
> @csjaugustus Just updated the source code with a fix and released a new compiled executable v1.0.0.2 you can try it out now.

Thank you

**Comment by 7gxycn08** [comment]
> > @csjaugustus Just updated the source code with a fix and released a new compiled executable v1.0.0.2 you can try it out now.
> 
> Thank you

Your welcome sir.

**Comment by lokeshvasnik** [comment]
Close the issue

**Comment by csjaugustus** [comment]
Issue resolved
